language: python
sudo: true

#before_install:
#  - sudo wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
#  - sudo dpkg -i pandoc-2.7.3-1-amd64.deb
#  - pandoc --version

before_install:
  - sudo apt install dirmngr gnupg apt-transport-https ca-certificates software-properties-common -y
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
  - sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'
  - sudo apt install r-base -y
  - sudo apt install r-base-dev -y
  - which R
  - R --version

install:
  - pip install tox
  - pip install -U importlib_metadata>=4.2.0
#  - pip install coveralls

script:
  - tox -r

matrix:
  include:
    - python: 3.8
      env: TOXENV=style
      dist: xenial
      sudo: true

    - python: 3.8
      env: TOXENV=coverage
      dist: xenial
      sudo: true

    - python: 3.8
      env: TOXENV=py38
      dist: xenial
      sudo: true

    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true
#after_success:
#  - coveralls
