language: python
sudo: true

#before_install:
#  - sudo wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
#  - sudo dpkg -i pandoc-2.7.3-1-amd64.deb
#  - pandoc --version

# whitelist
branches:
  only:
    - main


before_install:
  - sudo apt update -qq
  - sudo apt install --no-install-recommends software-properties-common dirmngr
  - wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
  - sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
  - sudo apt install --no-install-recommends r-base r-base-dev -y
  - which R
  - R --version
  - sudo usermod -a -G staff travis

install:
  - pip install tox
  - pip install -U importlib_metadata>=4.2.0
#  - pip install coveralls

script:
  - tox -r

matrix:
  include:
    - python: 3.8
      env: TOXENV=style
      dist: focal
      sudo: true

    - python: 3.8
      env: TOXENV=coverage
      dist: focal
      sudo: true

    - python: 3.8
      env: TOXENV=py38
      dist: focal
      sudo: true


    # seems to consume to much credits

    # - python: 3.7
    #   env: TOXENV=py37
    #   dist: xenial
    #   sudo: true

#after_success:
#  - coveralls
