name: Build and upload to PyPI

on:
  workflow_dispatch:
    inputs:
      upload:
        description: 'Upload to PyPI?'
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tool
        run: pip install build

      - name: Build wheel
        run: python -m build --wheel

      - name: Upload to PyPI
        if: ${{ github.event.inputs.upload == 'true' }}
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
